; generated by Slic3r 0.9.10b on 2013-11-21 at 13:33:23
; layer_height = 0.2
; perimeters = 3
; top_solid_layers = 3
; bottom_solid_layers = 3
; fill_density = 0.4
; perimeter_speed = 30
; infill_speed = 60
; travel_speed = 130
; nozzle_diameter = 0.5
; filament_diameter = 3
; extrusion_multiplier = 1
; perimeters extrusion width = 0.85mm
; infill extrusion width = 1.02mm
; solid infill extrusion width = 0.85mm
; top infill extrusion width = 0.85mm
; first layer extrusion width = 0.40mm

G21 ; set units to millimeters
M107
M104 S200 ; set temperature
G28 ; home all axes


